---
Name: postgres
Display-Name: PostgreSQL 9.5
Version: '9.5'
Vendor: postgresql.org
Category: Service
Base-Image: postgres:9.5.3
User: root
Endpoints:
- Private-Host-Name: DB_HOST
  Private-Port-Name: DB_PORT
  Private-Port: 5432
