---
Name: php
Display-Name: PHP 5.6
Description: PHP is a general-purpose server side scripting language orginally
  designed for Web development to produce dynamic Web pages.
Version: '5.6'
Vendor: php.net
Logo: manifest/logo.png
Category: Framework
Base-Image: php:5.6-apache
Endpoints:
- Private-Host-Name: HOST
  Private-Port-Name: PORT
  Private-Port: 8080
  Proxy-Mappings:
  - Frontend: /
    Backend: /
