---
Name: cwas
Display-Name: Cloudway Server 1.1
Version: '1.1'
Vendor: cloudway
Logo: manifest/logo.png
Category: Framework
Base-Image: icloudway/cwas:1.1
Build-Cache:
- .m2
Endpoints:
- Private-Host-Name: HOST
  Private-Port-Name: PORT
  Private-Port: 8080
  Proxy-Mappings:
    - Frontend: /
      Backend: /
      Protocols: [ajp, http]
    - Frontend: /cloudway/mux
      Backend: /cloudway/mux
      Protocols: [ws]
