---
Name: mysql
Display-Name: MySQL 5.5
Version: '5.5'
Vendor: Oracle
Logo: manifest/logo.png
Category: Service
Base-Image: mysql:5.5
Endpoints:
- Private-Host-Name: DB_HOST
  Private-Port-Name: DB_PORT
  Private-Port: 3306
