---
Name: redis
Display-Name: Redis 3.2
Description: Redis is an open source key-value store that functions as a data structure server.
Version: '3.2'
Vendor: redis.io
Logo: manifest/logo.png
Category: Service
Base-Image: icloudway/redis:3.2
User: root
Endpoints:
- Private-Host-Name: HOST
  Private-Port-Name: PORT
  Private-Port: 6379
